version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./service-account.json:/app/service-account.json:ro
    depends_on:
      - redis
      - firestore-emulator

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  firestore-emulator:
    image: google/cloud-sdk:latest
    ports:
      - "8081:8081"
    command: gcloud emulators firestore start --host-port=0.0.0.0:8081
    environment:
      - FIRESTORE_PROJECT_ID=agentiqware-dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  redis_data:
