version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - REDIS_HOST=redis
      - FIRESTORE_EMULATOR_HOST=firestore:8081
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - firestore
    command: python main.py

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  firestore:
    image: google/cloud-sdk:latest
    ports:
      - "8081:8081"
    command: gcloud emulators firestore start --host-port=0.0.0.0:8081
    environment:
      - FIRESTORE_PROJECT_ID=agentiqware-dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  redis_data:
