runtime: python311
env: standard
instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.7
  max_concurrent_requests: 50

env_variables:
  PROJECT_ID: "agentiqware-prod"
  ENVIRONMENT: "production"
  DEBUG: "False"
  ALLOWED_ORIGINS: "https://agentiqware.com,https://www.agentiqware.com"
  ALLOWED_HOSTS: "agentiqware.com,*.agentiqware.com,agentiqware-prod.appspot.com"

handlers:
  - url: /api/.*
    script: auto
    secure: always
  
  - url: /health
    script: auto
    secure: always
    
  - url: /docs
    script: auto
    secure: always
    
  - url: /.*
    script: auto
    secure: always