# docker-compose.yml - Local Development
version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - REACT_APP_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
      - PROJECT_ID=agentiqware-dev
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./service-account.json:/app/service-account.json:ro
    command: python main.py

  firestore-emulator:
    image: google/cloud-sdk:latest
    ports:
      - "8081:8081"
    command: gcloud emulators firestore start --host-port=0.0.0.0:8081
    environment:
      - FIRESTORE_PROJECT_ID=agentiqware-dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
